use std::f32::consts::PI;

pub const NOT_A_DISTANCE_FLOAT: f32 = -1.0;
pub const MIN_DOUBLE_LETTER_BEELINE_SPEED_PERCENTILE: i32 = 5;
pub const VERTICAL_SWEET_SPOT_SCALE: f32 = 1.0;
pub const VERTICAL_SWEET_SPOT_SCALE_G: f32 = 0.5;

pub const NEAR_KEY_THRESHOLD_FOR_DISTANCE: f32 = 2.0;

pub const MARGIN_FOR_PREV_LOCAL_MIN: f32 = 0.01;

pub const DISTANCE_BASE_SCALE: i32 = 100;
pub const NEAR_KEY_THRESHOLD_FOR_POINT_SCORE: f32 = 0.6;
pub const CORNER_CHECK_DISTANCE_THRESHOLD_SCALE: i32 = 25;
pub const NOT_LOCALMIN_DISTANCE_SCORE: f32 = -1.0;
pub const LOCALMIN_DISTANCE_AND_NEAR_TO_KEY_SCORE: f32 = 1.0;
pub const CORNER_ANGLE_THRESHOLD_FOR_POINT_SCORE: f32 = PI * 2.0 / 3.0;
pub const CORNER_SUM_ANGLE_THRESHOLD: f32 = PI / 4.0;
pub const CORNER_SCORE: f32 = 1.0;

pub const NUM_POINTS_FOR_SPEED_CALCULATION: usize = 2;

pub const LAST_POINT_SKIP_DISTANCE_SCALE: i32 = 4;

// TODO: add the rest when we get to them
